version: '3.8'

services:
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - shared_build_data:/shared-build

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - shared_build_data:/usr/share/nginx/html
    depends_on:
      frontend-builder:
        condition: service_completed_successfully

volumes:
  shared_build_data: