server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 프론트엔드 폴더 내의 server/db.json (json-server)을
    # 별도 컨테이너로 띄울 경우 아래 주석을 해제하여 프록시를 설정할 수 있습니다.
    # location /api/ {
    #     proxy_pass http://json-server:4000/;
    # }
}